"""
Django settings for config project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
=======
Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
>>>>>>> bb8d60eaff9c79db86becab91c8e18145f023ed4
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
<<<<<<< HEAD
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-atro24svgt%2szavu^($(wfm6ht2jew#gv_dv*5zz__e5)vk_$"
=======
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-771t95f^td33$@x!8!5lp61um46)*s)$*8st2j8iz$+e@-g%^+"
>>>>>>> bb8d60eaff9c79db86becab91c8e18145f023ed4

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
<<<<<<< HEAD
    "pages",
]

AUTH_USER_MODEL = 'accounts.CustomUser'
=======
]
AUTH_USER_MODEL="accounts.CustomUser"
>>>>>>> bb8d60eaff9c79db86becab91c8e18145f023ed4

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
<<<<<<< HEAD
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
=======
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
>>>>>>> bb8d60eaff9c79db86becab91c8e18145f023ed4
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
=======
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
>>>>>>> bb8d60eaff9c79db86becab91c8e18145f023ed4

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
<<<<<<< HEAD
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
=======
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
>>>>>>> bb8d60eaff9c79db86becab91c8e18145f023ed4

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
<<<<<<< HEAD
# https://docs.djangoproject.com/en/5.0/topics/i18n/
=======
# https://docs.djangoproject.com/en/5.2/topics/i18n/
>>>>>>> bb8d60eaff9c79db86becab91c8e18145f023ed4

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/5.0/howto/static-files/
=======
# https://docs.djangoproject.com/en/5.2/howto/static-files/
>>>>>>> bb8d60eaff9c79db86becab91c8e18145f023ed4

STATIC_URL = "static/"

# Default primary key field type
<<<<<<< HEAD
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL='home'
LOGOUT_REDIRECT_URL='home'
=======
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
>>>>>>> bb8d60eaff9c79db86becab91c8e18145f023ed4
